spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/royalracing
    username: royalracing
    password: royalracing
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080
